# Numerical Python (NUMPY)

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#importing the numpy library
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


CREATE A MULTIDIMENSION ARRAY

In [ ]:
mylist = [1,2,3]
n = np.array(mylist)
print(n)
#numpy array is a positive tuple

[1 2 3]


In [ ]:
type(n)

numpy.ndarray

In [ ]:
list_of_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
list_of_list.shape

(3, 3)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
for i in range(0,50,2):
  print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48


In [ ]:
#generate the arrays of zeros
zero=np.zeros(100)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
mn=np.arange(0,50)
mn


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
len(mn)

50

In [ ]:
mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
o=np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
len(o)

10

In [ ]:
o.resize(5,2)


In [ ]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [ ]:
#return a sample from uniform distriution
np.random.rand(10,5)

array([[0.48996212, 0.67292121, 0.85274447, 0.39209738, 0.65557483],
       [0.30429261, 0.9153773 , 0.35529136, 0.55522381, 0.81732956],
       [0.54691189, 0.62889812, 0.58736612, 0.88249682, 0.36735358],
       [0.79206179, 0.19827056, 0.51041406, 0.96476596, 0.07407308],
       [0.10614479, 0.13931829, 0.32963931, 0.83339841, 0.88281183],
       [0.39774593, 0.81923871, 0.09343159, 0.10046928, 0.44282645],
       [0.81812258, 0.9892437 , 0.63060793, 0.4812144 , 0.6914167 ],
       [0.56571542, 0.01609363, 0.21969552, 0.8896613 , 0.17578489],
       [0.29233692, 0.16405022, 0.88868097, 0.02921627, 0.72247654],
       [0.57593396, 0.10921437, 0.97875625, 0.65988641, 0.36216106]])

In [ ]:
#return a sample from standard normal distriution 
a=np.random.randn(10,5)
a

array([[-0.03459327,  0.87456357, -1.20691032,  0.74775247,  0.66717312],
       [-0.58824503, -0.73993508,  0.26757658,  0.01425161, -0.13546731],
       [-0.156682  , -0.70707314, -0.17916907,  1.116015  ,  0.58285817],
       [-0.32452303,  0.0538765 ,  0.50135789, -0.76804609,  1.29218174],
       [ 0.04315234,  1.816153  ,  1.65363353, -0.58864225, -0.31243726],
       [ 0.20625684, -1.05950106, -1.99665857,  0.42245099, -0.38324429],
       [ 0.18885585, -0.51481866,  2.19081842, -0.06281847,  0.5240792 ],
       [ 0.07407915, -0.55345487, -0.247886  , -1.40209968, -1.48349483],
       [ 0.39483925, -0.29980403,  0.11306143,  0.96217812,  0.67874593],
       [-0.55728622,  0.62718045, -1.68935143,  0.12525144, -0.68207625]])

In [ ]:
mn=np.random.randint(10,50,50)
mn

array([47, 45, 37, 11, 42, 34, 23, 40, 20, 22, 29, 23, 42, 18, 16, 10, 23,
       28, 42, 29, 45, 12, 35, 19, 19, 19, 23, 16, 30, 10, 40, 22, 38, 12,
       19, 16, 13, 42, 13, 44, 48, 15, 36, 48, 28, 11, 42, 25, 12, 19])

In [ ]:
mn.reshape(5,10)

array([[47, 45, 37, 11, 42, 34, 23, 40, 20, 22],
       [29, 23, 42, 18, 16, 10, 23, 28, 42, 29],
       [45, 12, 35, 19, 19, 19, 23, 16, 30, 10],
       [40, 22, 38, 12, 19, 16, 13, 42, 13, 44],
       [48, 15, 36, 48, 28, 11, 42, 25, 12, 19]])

Indexing & Slicing

In [ ]:
mn=np.random.randint(1,50,50)
mn

array([26,  2, 40, 12, 44, 17,  3,  8, 26, 22, 28, 38,  3, 44, 29,  1, 26,
       39, 43, 11, 29, 48, 48, 18, 20, 34, 46, 47, 31, 15, 13, 19, 46, 37,
       16,  5, 33,  3, 29, 41,  4, 10, 44, 41, 48, 34, 41, 23, 20, 34])

In [ ]:
mn[1]

2

In [ ]:
mn[-1]

34

In [ ]:
mn[3:7] #seleting items from range

array([12, 44, 17,  3])

In [ ]:
mn[3:-7]

array([12, 44, 17,  3,  8, 26, 22, 28, 38,  3, 44, 29,  1, 26, 39, 43, 11,
       29, 48, 48, 18, 20, 34, 46, 47, 31, 15, 13, 19, 46, 37, 16,  5, 33,
        3, 29, 41,  4, 10, 44])

In [ ]:
mn[mn>25] #conditional indexing

array([26, 40, 44, 26, 28, 38, 44, 29, 26, 39, 43, 29, 48, 48, 34, 46, 47,
       31, 46, 37, 33, 29, 41, 44, 41, 48, 34, 41, 34])

In [ ]:
mn[mn>25]=25 #casting all the values that are greter than 25 to 25
mn

array([25,  2, 25, 12, 25, 17,  3,  8, 25, 22, 25, 25,  3, 25, 25,  1, 25,
       25, 25, 11, 25, 25, 25, 18, 20, 25, 25, 25, 25, 15, 13, 19, 25, 25,
       16,  5, 25,  3, 25, 25,  4, 10, 25, 25, 25, 25, 25, 23, 20, 25])

In [ ]:
array1=np.array([15,16,7,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40])
print(array1)

[15 16  7 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40]


In [ ]:
array2=np.array([10,11,12,13,14,15,16,7,18,19,20,21,22,23,24,25])
print(array2)

[10 11 12 13 14 15 16  7 18 19 20 21 22 23 24 25]


ValueError: ignored